name: whatsup
description: 'A lightweight package to return time-based greetings like "Good morning" or "Good afternoon" from a given datetime.'
version: 1.0.4
homepage: https://github.com/whyzotee/whatsup

environment:
  sdk: ^3.13.5
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
