name: whatsup
description: 'A lightweight package to return time-based greetings like "Good morning" or "Good afternoon" from a given datetime.'
version: 1.0.6
homepage: https://github.com/whyzotee/whatsup

environment:
  sdk: ^3.13.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.33.0
